name: Update Strava Data and Send Telegram Alert

on:
  schedule:
    - cron: '59 23 * * *'  # Запуск каждый день в 10 утра по московскому времени (7 утра UTC)
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-telegram-bot

    - name: Run Script
      env:
        ACCESS_TOKEN: ${{ secrets.STRAVA_ACCESS_TOKEN }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: python .github/workflows/swimming.py

    - name: Check for changes
      id: check_changes
      run: |
        git diff --exit-code || echo "changes"

    - name: Commit changes
      if: steps.check_changes.outputs.no_change != 'true'
      run: |
        git config --global user.email "nikkuryshev98@gmail.com"
        git config --global user.name "Your Name"
        git add last_week_results.json
        git commit -m "Update last week results"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
